apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-infrastructure-storage
  namespace: kube-system
  labels:
    purpose: influxdb-infrastructure
    type: local
spec:
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/influxdb-infrastructure/"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-infrastructure-storage-claim
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16Gi
  storageClassName: manual
  selector:
    matchLabels:
      purpose: influxdb-infrastructure
